#!/bin/bash

# -Wno-unreachable-code-generic-assoc is needed for "debug.h"

gcc \
    -Wno-unreachable-code-generic-assoc \
    -I"./inc" \
    -o /tmp/repl \
    repl.c &&
    chmod 777 /tmp/repl &&
    /tmp/repl

rm -f /tmp/repl
